fix dockerfile

diff --git a/docker/Dockerfile b/docker/Dockerfile
--- a/docker/Dockerfile
+++ b/docker/Dockerfile
@@ -4,16 +4,36 @@
 # SPDX-License-Identifier: BSD-2-Clause
 #
 
-FROM trustworthysystems/sel4
+FROM debian:bookworm
 
 RUN apt-get update -q && apt-get install -y --no-install-recommends \
-    wget \
-    sudo man vim \
+    build-essential \
+    curl \
+    git \
+    # for seL4
+    gcc-aarch64-linux-gnu \
+    python3-dev \
+    python3-venv \
+    cmake \
+    ninja-build \
+    device-tree-compiler \
+    libxml2-utils \
+    qemu-utils \
+    qemu-system-arm \
+    qemu-efi-aarch64 \
+    ipxe-qemu \
+    # for bindgen
+    libclang-dev \
+    # for test script
+    python3-pexpect \
+    # for hacking
     bash-completion \
+    man \
+    sudo \
     && rm -rf /var/lib/apt/lists/*
 
-# RUN curl -sSf https://sh.rustup.rs | \
-#         bash -s -- -y --no-modify-path --default-toolchain none
+WORKDIR /tmp
+
 RUN curl -sSf https://sh.rustup.rs | \
         bash -s -- -y --no-modify-path \
             --default-toolchain nightly-2024-09-01 \
@@ -21,9 +41,7 @@ RUN curl -sSf https://sh.rustup.rs | \
 
 ENV PATH=/root/.cargo/bin:$PATH
 
-RUN mkdir /deps
-
-WORKDIR /deps
+ENV SEL4_INSTALL_DIR=/opt/seL4
 
 RUN set -eux; \
     git clone \
@@ -32,43 +50,24 @@ RUN set -eux; \
     cd seL4; \
     git checkout cd6d3b8c25d49be2b100b0608cf0613483a6fffa;
 
-RUN apt-get update -q && apt-get install -y --no-install-recommends gcc-riscv64-linux-gnu && rm -rf /var/lib/apt/lists/*
-
-ENV SEL4_INSTALL_DIR=/deps/seL4/install
-
-ARG ARCH=aarch64
-ARG TARGET=aarch64-unknown-none
-
-COPY kernel-settings-${ARCH}.cmake ./kernel-settings.cmake
 RUN set -eux; \
     cd seL4; \
+    python3 -m venv pyenv; \
+    export PATH=$(realpath ./pyenv/bin):$PATH; \
+    pip install tools/python-deps; \
     cmake \
-        -DCROSS_COMPILER_PREFIX=${ARCH}-linux-gnu- \
-        -DCMAKE_INSTALL_PREFIX=install \
-        -C ../kernel-settings.cmake \
+        -DCROSS_COMPILER_PREFIX=aarch64-linux-gnu- \
+        -DCMAKE_INSTALL_PREFIX=$SEL4_INSTALL_DIR \
+        -DKernelPlatform=qemu-arm-virt \
+        -DKernelArmHypervisorSupport=ON \
+        -DKernelVerificationBuild=OFF \
+        -DARM_CPU=cortex-a57 \
         -G Ninja \
         -S . \
         -B build; \
     ninja -C build all; \
-    ninja -C build install;
-
-# RUN set -eux; \
-#     url="https://github.com/rel4team/rust-sel4"; \
-#     branch="mi_dev"; \
-#     remote_options="--git $url --branch $branch"; \
-#     CC=${ARCH}-linux-gnu-gcc \
-#     SEL4_PREFIX=$SEL4_INSTALL_DIR \
-#         cargo install \
-#             -Z build-std=core,alloc,compiler_builtins \
-#             -Z build-std-features=compiler-builtins-mem \
-#             --target ${TARGET} \
-#             --root . \
-#             $remote_options \
-#             sel4-kernel-loader; \
-#     cargo install \
-#         --root . \
-#         $remote_options \
-#         sel4-kernel-loader-add-payload;
+    ninja -C build install; \
+    rm -rf $(pwd);
 
 RUN set -eux; \
     url="https://github.com/seL4/rust-sel4"; \
@@ -94,40 +93,68 @@ RUN set -eux; \
 RUN set -eux; \
     git clone \
         https://github.com/rel4team/seL4_c_impl.git \
-        --config advice.detachedHead=false -b mi_dev;
+        --config advice.detachedHead=false -b update-kernel;
 
-# Build rel4 kernel. Just for riscv64 temporarily
-COPY kernel-settings-riscv64.cmake .
-RUN set -eux; \
-    cd rel4_kernel;\
-    rustup target add riscv64imac-unknown-none-elf; \
-    make run;\
-    cd ../seL4_c_impl; \
-    cmake \
-        -DCROSS_COMPILER_PREFIX=riscv64-linux-gnu- \
-        -DCMAKE_INSTALL_PREFIX=/opt/reL4 \
-        -DKernelPlatform=spike \
-        -C ../kernel-settings-riscv64.cmake \
-        -G Ninja \
-        -S . \
-        -B build; \
-    ninja -C build all; \
-    ninja -C build install; \
-    rm -rf $(pwd);
+COPY kernel-settings-aarch64.cmake .
+# RUN set -eux; \
+#     cd rel4_kernel;\
+#     python3 -m venv pyenv; \
+#     export PATH=$(realpath ./pyenv/bin):$PATH; \
+#     pip install pyyaml; \
+#     pip install pyfdt; \
+#     pip install jinja2; \
+#     pip install six; \
+#     pip install future; \
+#     pip install ply; \
+#     rustup target add aarch64-unknown-none; \
+#     make run ARCH=aarch64;\
+#     cd ../seL4_c_impl; \
+#     echo "Building seL4_c_impl"; \
+#     rm -rf build; \
+#     cmake \
+#         -DCROSS_COMPILER_PREFIX=aarch64-linux-gnu- \
+#         -DCMAKE_INSTALL_PREFIX=/opt/reL4 \
+#         -C ./kernel-settings-aarch64.cmake \
+#         -G Ninja \
+#         -S . \
+#         -B build; \
+#     ninja -C build all; \
+#     ninja -C build install; \
+#     rm -rf $(pwd);
+
 
 ARG UID
 ARG GID
 
-RUN groupadd -f -g $GID x && useradd -u $UID -g $GID -G sudo -m -p x x
-RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers # for convenience
+RUN set -eux; \
+    if [ $UID -eq 0 ]; then \
+        if [ $GID -ne 0 ]; then \
+            echo "error: \$UID == 0 but \$GID != 0" >&2; \
+            exit 1; \
+        fi; \
+    else \
+        if getent passwd $UID; then \
+            echo "error: \$UID $UID already exists" >&2; \
+            exit 1; \
+        fi; \
+        if ! getent group $GID; then \
+            groupadd --gid $GID x; \
+        fi; \
+        useradd --uid $UID --gid $GID --groups sudo --create-home x; \
+    fi;
 
-USER x
+RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
 
-# This time, for the non-root user
-RUN curl -sSf https://sh.rustup.rs | \
-        bash -s -- -y --no-modify-path --default-toolchain none
+USER $UID
+
+RUN set -eux; \
+    if [ $UID -ne 0 ]; then \
+        curl -sSf https://sh.rustup.rs | \
+            bash -s -- -y --no-modify-path --default-toolchain none; \
+    fi;
 
 ENV PATH=/home/x/.cargo/bin:$PATH
-ENV ARCH=${ARCH}
+
+ENV SHELL=/bin/bash
 
 WORKDIR /work
